/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */
import React from 'react';
import { 
  DocumentTextIcon, 
  Square3Stack3DIcon, 
  CommandLineIcon, 
  ArrowPathIcon,
  SparklesIcon
} from '@heroicons/react/24/outline';
import { WorkflowDoc } from '../../types';

interface DocumentationPanelProps {
  doc?: WorkflowDoc;
  onRefresh: () => void;
  isLoading: boolean;
}

export const DocumentationPanel: React.FC<DocumentationPanelProps> = ({ doc, onRefresh, isLoading }) => {
  if (!doc) {
    return (
      <div className="flex flex-col items-center justify-center h-full p-10 text-center space-y-6">
        <div className="w-20 h-20 bg-zinc-900/50 rounded-full flex items-center justify-center animate-pulse">
           <DocumentTextIcon className="w-10 h-10 text-zinc-800" />
        </div>
        <div>
           <h4 className="text-white text-sm font-black uppercase tracking-widest mb-2">Documentation Required</h4>
           <p className="text-zinc-600 text-[10px] uppercase font-mono tracking-tighter">AI has not yet synthesized a technical manifesto for this artifact.</p>
        </div>
        <button 
          onClick={onRefresh}
          disabled={isLoading}
          className="bg-blue-600 hover:bg-blue-500 text-white px-6 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all shadow-xl active:scale-95"
        >
          {isLoading ? <ArrowPathIcon className="w-4 h-4 animate-spin" /> : <SparklesIcon className="w-4 h-4 inline mr-2" />}
          Generate Manifesto
        </button>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full animate-in slide-in-from-left duration-500 overflow-hidden">
      <header className="px-5 py-4 border-b border-zinc-800 bg-[#121214] flex items-center justify-between shrink-0">
        <div className="flex items-center space-x-3">
          <div className="p-2 bg-purple-500/10 rounded-lg">
             <DocumentTextIcon className="w-4 h-4 text-purple-400" />
          </div>
          <div className="flex flex-col">
            <span className="text-[10px] font-black uppercase tracking-[0.2em] text-zinc-500">Technical Manifesto</span>
            <span className="text-xs font-bold text-white tracking-tight">Synthesized Documentation</span>
          </div>
        </div>
        <button 
          onClick={onRefresh}
          className="text-zinc-500 hover:text-white transition-colors"
          title="Regenerate documentation"
        >
          <ArrowPathIcon className={`w-4 h-4 ${isLoading ? 'animate-spin' : ''}`} />
        </button>
      </header>

      <div className="flex-1 overflow-y-auto p-6 space-y-10 custom-scrollbar bg-[#0c0c0e]">
        <section className="space-y-4">
           <h5 className="text-[10px] font-black text-zinc-600 uppercase tracking-[0.3em] flex items-center gap-2">
              <Square3Stack3DIcon className="w-3.5 h-3.5" />
              Purpose & Intent
           </h5>
           <p className="text-sm text-zinc-200 leading-relaxed font-medium">
             {doc.purpose}
           </p>
        </section>

        <section className="space-y-4">
           <h5 className="text-[10px] font-black text-zinc-600 uppercase tracking-[0.3em] flex items-center gap-2">
              <CommandLineIcon className="w-3.5 h-3.5" />
              I/O Interface Schema
           </h5>
           <pre className="bg-zinc-950 p-5 rounded-2xl border border-zinc-800 text-[11px] font-mono text-blue-400 overflow-x-auto">
             {doc.ioSchema}
           </pre>
        </section>

        <section className="space-y-4">
           <h5 className="text-[10px] font-black text-zinc-600 uppercase tracking-[0.3em] flex items-center gap-2">
              <CommandLineIcon className="w-3.5 h-3.5" />
              Internal Runtime Logic
           </h5>
           <div className="manifest-prose text-zinc-300 text-sm prose-sm dark:prose-invert max-w-none">
             {doc.internalLogic}
           </div>
        </section>

        <footer className="pt-8 border-t border-zinc-900 flex justify-between items-center opacity-40">
           <span className="text-[9px] font-black uppercase tracking-widest text-zinc-600">Generated by Gemini-3</span>
           <span className="text-[9px] font-mono text-zinc-700">{new Date(doc.lastUpdated).toLocaleDateString()}</span>
        </footer>
      </div>
    </div>
  );
};
